unihackhq/skilled-acolyte-backend

Dockerfile
config/app.json
config/db.json
docker-compose.yml
package.json
yarn.lock

Dockerize! 🎉

---

.travis.yml

It should probably have some stuff in it...

Created travis-ci file.

---

app/models/Event.js
app/models/Student.js
app/models/Team.js
app/models/Ticket.js
app/models/University.js
app/models/User.js
app/models/index.js

Initial database model for the backend

Database Model

---

app/controllers/Student.js
app/controllers/User.js
app/routes.js
app/validators/Student.js
app/validators/University.js
app/validators/User.js

Added the API routes needed for students, should all work as advertised.

Added user and student endpoints.

---

app/controllers/Example.js
app/controllers/Token.js
app/models/Token.js
app/routes.js
app/util/Token.js
config/app.json
docker-compose.yml
env.js
index.js
package-lock.json
package.json

This is pretty much finished. 
Flow:
1. Use requests a token
2. User receives an email with token
3. User supplies token (via frontend) and receives a JWT

Add password-less, email-based, auth

---

app/controllers/Student.js
app/routes.js

just a list of all students (only name and id)
need this for the dropdown to invite members to team

user directory

---

app/controllers/student.js
app/controllers/ticket.js
app/models/Student.js
app/models/User.js
app/models/index.js
app/routes.js
app/services/eventbrite.js
app/services/prepopulate.js
app/services/student.js
app/services/ticket.js
app/validators/event.js
app/validators/student.js
app/validators/team.js
app/validators/ticket.js
app/validators/university.js
app/validators/user.js
package-lock.json
package.json

Ticket transfer

---

app/controllers/token.js
app/models/Token.js
app/models/index.js
app/routes.js
config/app.json
docker-compose.prod.yml
docker-compose.yml
env.js

promisify token request and validate
add relation between user and token in db
closes #13

Fix token request and validation

---

app/controllers/student.js
app/routes.js
app/services/student.js

leave team

---

app/clients/eventbrite.js
app/controllers/student.js
app/controllers/team.js
app/models/Event.js
app/models/index.js
app/routes.js
app/services/eventbrite.js
app/services/prepopulate.js
app/services/student.js
app/services/team.js
app/util/populateScope.js
app/util/strip.js
app/validators/ticket.js

#43 #44 and #47 didn't merge into develop cause I had the merge request set to other random branches to show the diff properly.
I forgot to change the branch before merging so they all merged into the random branches which themselves got deleted.
And here we are. :expressionless: 
This will actually add those commits to develop
Leason to learn: actually go through with what you started, don't quit stacking pull requests half way through...

Actually merge the changes

---

app/services/eventbrite.js
app/services/prepopulate.js
app/services/student.js
app/services/team.js
app/util/error.js
index.js

Fix a few problems with creating new db objects

---

.eslintrc.js
app/controllers/prepopulate.js
app/services/eventbrite.js
app/services/prepopulate.js
config/app.yml
env.js

Filters out all cancelled tickets.
and can handle not having answer to some questions

Fix the problems with prepopulate

---

app/constants.js
app/controllers/event.js
app/controllers/prepopulate.js
app/controllers/student.js
app/controllers/team.js
app/controllers/ticket.js
app/controllers/university.js
app/controllers/user.js
app/routes.js
app/services/student.js
app/services/team.js
app/util/populateScope.js
app/util/strip.js

rn to get all info about the team we need three requests.
also kinda cumbersome for clients.
Also modify POST team to return the same data as GET

Include more info when getting team

---

app/constants.js
app/controllers/event.js
app/controllers/student.js
app/routes.js
app/services/event.js
app/services/prepopulate.js
app/services/student.js
app/util/populateScope.js

Better support for multiple events

---

app/models/Team.js
app/util/strip.js
app/validators/team.js

Extra team fields

---

.docker/dev/Dockerfile
.docker/prod/Dockerfile
app/controllers/event.js
app/controllers/schedule.js
app/controllers/student.js
app/models/Event.js
app/models/ScheduleItem.js
app/models/index.js
app/routes.js
app/services/event.js
app/services/schedule.js
app/util/strip.js
app/validators/schedule.js
docker-compose.dev.yml
docker-compose.test.yml
docker-compose.yml

Add schedule

---

app/models/Event.js
app/util/strip.js
app/validators/event.js

Event info

---

app/controllers/ticket.js
app/services/ticket.js

check for existing students when transferring ticket

---

app/util/validator.js
app/validators/event.js
app/validators/schedule.js
app/validators/student.js
app/validators/team.js
app/validators/ticket.js
app/validators/university.js
app/validators/user.js

Joi wasn't allowing null even for optional fields. Also general improvements.

Better payload validation

---

app/controllers/ticket.js
app/controllers/token.js
app/validators/user.js

@dsykesturner noticed that login was case sensitive. Emails should be case insensitive.

make all emails lowercase

---

app/services/notification.js
index.js
package-lock.json
package.json

Can't change db schema on the day.  
In the future schedule items will have a timezone field

add hardcoded timezone to notification (needs to change later)

---

package-lock.json
package.json

Upgrade hapi to 17.6.0
